from __future__ import annotations


EVENT_DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
EVENT_DOCUMENT_VALIDATED = "DOCUMENT_VALIDATED"
EVENT_DOCUMENT_QUEUED = "DOCUMENT_QUEUED"
EVENT_DOCUMENT_PROCESSING_STARTED = "DOCUMENT_PROCESSING_STARTED"
EVENT_DOCUMENT_EXTRACTION_COMPLETED = "DOCUMENT_EXTRACTION_COMPLETED"
EVENT_DOCUMENT_RESOLUTION_COMPLETED = "DOCUMENT_RESOLUTION_COMPLETED"
EVENT_DOCUMENT_RETAINED = "DOCUMENT_RETAINED"
EVENT_DOCUMENT_CLEANED = "DOCUMENT_CLEANED"
EVENT_DOCUMENT_FAILED = "DOCUMENT_FAILED"
EVENT_DOCUMENT_RETRY_REQUESTED = "DOCUMENT_RETRY_REQUESTED"
EVENT_DOCUMENT_RETRY_STARTED = "DOCUMENT_RETRY_STARTED"
EVENT_DOCUMENT_RETRY_COMPLETED = "DOCUMENT_RETRY_COMPLETED"
EVENT_DOCUMENT_DUPLICATE_REUSED = "DOCUMENT_DUPLICATE_REUSED"
EVENT_DOCUMENT_EXPORTED = "DOCUMENT_EXPORTED"

ACTOR_BATCH_PROCESSOR = "batch_processor"
ACTOR_RETRY_SERVICE = "retry_service"
ACTOR_RETENTION_SERVICE = "retention_service"
ACTOR_API = "api"

STATEFUL_EVENT_TYPES = {
    EVENT_DOCUMENT_UPLOADED,
    EVENT_DOCUMENT_VALIDATED,
    EVENT_DOCUMENT_QUEUED,
    EVENT_DOCUMENT_PROCESSING_STARTED,
    EVENT_DOCUMENT_EXTRACTION_COMPLETED,
    EVENT_DOCUMENT_RESOLUTION_COMPLETED,
    EVENT_DOCUMENT_RETAINED,
    EVENT_DOCUMENT_CLEANED,
    EVENT_DOCUMENT_FAILED,
}
