from __future__ import annotations


STATE_UPLOADED = "uploaded"
STATE_VALIDATED = "validated"
STATE_QUEUED = "queued"
STATE_PROCESSING = "processing"
STATE_EXTRACTED = "extracted"
STATE_RESOLVED = "resolved"
STATE_RETAINED = "retained"
STATE_CLEANED = "cleaned"
STATE_FAILED = "failed"

STATEFUL_LIFECYCLE_STATES = {
    STATE_UPLOADED,
    STATE_VALIDATED,
    STATE_QUEUED,
    STATE_PROCESSING,
    STATE_EXTRACTED,
    STATE_RESOLVED,
    STATE_RETAINED,
    STATE_CLEANED,
    STATE_FAILED,
}

ALLOWED_STATE_TRANSITIONS: dict[str | None, set[str]] = {
    None: {STATE_UPLOADED},
    STATE_UPLOADED: {STATE_QUEUED},
    STATE_QUEUED: {STATE_PROCESSING},
    STATE_PROCESSING: {STATE_VALIDATED, STATE_FAILED},
    STATE_VALIDATED: {STATE_EXTRACTED, STATE_FAILED},
    STATE_EXTRACTED: {STATE_RESOLVED, STATE_FAILED},
    STATE_RESOLVED: {STATE_RETAINED, STATE_QUEUED},
    STATE_RETAINED: {STATE_CLEANED, STATE_QUEUED},
    STATE_FAILED: {STATE_QUEUED, STATE_RETAINED},
    STATE_CLEANED: set(),
}
