from __future__ import annotations

from app.lifecycle.events import (
    EVENT_DOCUMENT_CLEANED,
    EVENT_DOCUMENT_DUPLICATE_REUSED,
    EVENT_DOCUMENT_EXPORTED,
    EVENT_DOCUMENT_EXTRACTION_COMPLETED,
    EVENT_DOCUMENT_FAILED,
    EVENT_DOCUMENT_PROCESSING_STARTED,
    EVENT_DOCUMENT_QUEUED,
    EVENT_DOCUMENT_RETAINED,
    EVENT_DOCUMENT_RESOLUTION_COMPLETED,
    EVENT_DOCUMENT_RETRY_COMPLETED,
    EVENT_DOCUMENT_RETRY_REQUESTED,
    EVENT_DOCUMENT_RETRY_STARTED,
    EVENT_DOCUMENT_UPLOADED,
    EVENT_DOCUMENT_VALIDATED,
)


EVENT_FAMILY_PROGRESS = "progress"
EVENT_FAMILY_FAILURE = "failure"
EVENT_FAMILY_RETRY = "retry"
EVENT_FAMILY_RETENTION = "retention"
EVENT_FAMILY_CLEANUP = "cleanup"
EVENT_FAMILY_EXPORT = "export"
EVENT_FAMILY_DUPLICATE = "duplicate"


EVENT_FAMILY_BY_TYPE = {
    EVENT_DOCUMENT_UPLOADED: EVENT_FAMILY_PROGRESS,
    EVENT_DOCUMENT_QUEUED: EVENT_FAMILY_PROGRESS,
    EVENT_DOCUMENT_PROCESSING_STARTED: EVENT_FAMILY_PROGRESS,
    EVENT_DOCUMENT_VALIDATED: EVENT_FAMILY_PROGRESS,
    EVENT_DOCUMENT_EXTRACTION_COMPLETED: EVENT_FAMILY_PROGRESS,
    EVENT_DOCUMENT_RESOLUTION_COMPLETED: EVENT_FAMILY_PROGRESS,
    EVENT_DOCUMENT_FAILED: EVENT_FAMILY_FAILURE,
    EVENT_DOCUMENT_RETRY_REQUESTED: EVENT_FAMILY_RETRY,
    EVENT_DOCUMENT_RETRY_STARTED: EVENT_FAMILY_RETRY,
    EVENT_DOCUMENT_RETRY_COMPLETED: EVENT_FAMILY_RETRY,
    EVENT_DOCUMENT_RETAINED: EVENT_FAMILY_RETENTION,
    EVENT_DOCUMENT_CLEANED: EVENT_FAMILY_CLEANUP,
    EVENT_DOCUMENT_DUPLICATE_REUSED: EVENT_FAMILY_DUPLICATE,
    EVENT_DOCUMENT_EXPORTED: EVENT_FAMILY_EXPORT,
}

KNOWN_EVENT_TYPES = frozenset(EVENT_FAMILY_BY_TYPE.keys())


def require_known_event_type(event_type: str) -> None:
    if event_type not in KNOWN_EVENT_TYPES:
        raise ValueError(f"Unknown lifecycle event type: {event_type}")


def event_family_for(event_type: str) -> str:
    require_known_event_type(event_type)
    return EVENT_FAMILY_BY_TYPE[event_type]
