services:
  app:
    build: .
    container_name: olre-app
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
      ENABLE_AUTH: "false"
      DATABASE_URL: sqlite:////app/data/olre.sqlite3
      INPUT_DIR: /app/data/input
      PROCESSED_DIR: /app/data/processed
      ERROR_DIR: /app/data/error
      QR_DEBUG_DIR: /app/data/debug/qr
      RUNTIME_TMP_DIR: /app/data/runtime/tmp
      FAILED_RETAINED_DIR: /app/data/runtime/failed-retained
      SECRET_KEY: change-me-in-production
      LOG_LEVEL: INFO
    volumes:
      - olre_data:/app/data
    restart: unless-stopped

volumes:
  olre_data:
